#!/usr/bin/perl
use warnings;

while (<STDIN>){
    chomp;
    if(/(?<word>\w+a)\b/){
        print "Matched: |$`<$&>$'|\n";
        print "'word' contains '$1'\n";
    }else{
        print "No matched\n";
    };

};
