#!/usr/bin/perl
use warnings;

while (<STDIN>){
    chomp;
    if(/(\w+a)\b(.{0,5})/){
        print "Matched: |$`<$&>$'|\n";
        print "'$1','$2'\n";
    }else{
        print "No matched\n";
    };

};
